### ISSUE TITLE
Make a .py file

### ISSUE THREAD

**Issue by Ceres445** [MysteriousK69/NitroGenByMK-PYTHON#1]
can u leave the .py file here instead of the exe so i can take a look at it and edit it. Thanks

**Comment by MysteriousK69** [comment]
@Ceres445 Sure, I have made this into a different tool and made it open source. Be sure to give me credits and not use the code for commerical use.

**Comment by Ceres445** [comment]
> @Ceres445 Sure, I have made this into a different tool and made it open source. Be sure to give me credits and not use the code for commerical use.

Link to the repo please
thanks

**Comment by MysteriousK69** [comment]
https://github.com/MysteriousK69/Ez-Nitro Now, its a GUI tool that uses PyQt5 for the GUI. You can also find the UI file in the repo. Please, star it.
